### ISSUE TITLE
env-file: destination-file doesn't work

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/github-actions#1]
The destination file parameter doesn't seem to work correctly. The .env file is always created in the root folder of the project.
Here an example of a workflow file with destination-file parameter:
https://github.com/noi-techpark/it.bz.opendatahub.webcomponents/actions/runs/1909841028/workflow
And here the action run of this workflow with an ls check to see where the file gets created.
https://github.com/noi-techpark/it.bz.opendatahub.webcomponents/runs/5358493173?check_suite_focus=true

**Comment by Piiit** [comment]
@dulvui Does it work, can we close it?

**Comment by dulvui** [comment]
Yes it works. I'll close the issue
